import { Inter as FontSans } from "next/font/google";
import localFont from "next/font/local";

import "@/styles/global.css";
import type { Metadata } from "next";
import Link from "next/link";
import { cn } from "@/lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

// Font files can be colocated inside of `pages`
const fontHeading = localFont({
  src: "../assets/fonts/CalSans-SemiBold.woff2",
  variable: "--font-heading",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
          fontHeading.variable
        )}
      >
        <div className="container mx-auto ">
          <div className="flex flex-col lg:flex-row flex-wrap lg:justify-center py-6 lg:py-10">
            <aside className="bg-white-600 px-2 w-1/4">
              <div className="sticky top-0 w-full p-4 text-center">
                <Link href="/">Ryan Tong</Link>
              </div>
            </aside>
            <main className="px-6 w-full md:max-w-3xl">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
